spring.datasource.url=jdbc:postgresql://securechat-db-rw.default.svc.cluster.local:5432/securechat
spring.datasource.username=postgres
spring.datasource.password=K2YmpuWIgtnyS0LyxYvp2xEJwZTlUz7Fe3aCHGRJQhJ8eM5sHwLUX2Tzl72wbnLM

minio.url=http://minio-service.default.svc.cluster.local:9000
minio.access.key=admin
minio.secret.key=password
minio.bucket.name=securechat-files

spring.kafka.bootstrap-servers=redpanda-service.default.svc.cluster.local:9092
spring.kafka.producer.properties.max.block.ms=5000

jwt.secret=vash_ochen_dlinniy_i_slozhniy_sekret_dlya_podpisi_jwt_tokenov_256bit