spring.application.name=securechat
server.port=8080

jwt.secret=6d79536563726574-4b6579466f724a57-54417574683230323-5496e536563757265

minio.url=http://localhost:9000
minio.access.key=admin
minio.secret.key=password
minio.bucket.name=securechat-files

spring.kafka.bootstrap-servers=192.168.154.131:30092

spring.kafka.consumer.group-id=chat-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.session.timeout.ms=6000
spring.kafka.consumer.properties.heartbeat.interval.ms=2000

spring.kafka.producer.properties.max.block.ms=120000
spring.kafka.producer.properties.delivery.timeout.ms=120000
spring.kafka.producer.properties.request.timeout.ms=5000
spring.kafka.producer.properties.retry.backoff.ms=500

spring.kafka.properties.metadata.max.age.ms=3000
spring.kafka.properties.reconnect.backoff.ms=500
spring.kafka.properties.reconnect.backoff.max.ms=3000

spring.kafka.properties.socket.connection.setup.timeout.ms=1000
spring.kafka.properties.socket.connection.setup.timeout.max.ms=3000

spring.datasource.url=jdbc:postgresql://localhost:5432/securechat
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
