apiVersion: v1
kind: Secret
metadata:
  name: securechat-secrets
type: Opaque
stringData:
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "SecureMinioPassword123!"
  JWT_SECRET: "vash_ochen_dlinniy_i_slozhniy_sekret_dlya_podpisi_jwt_tokenov_256bit"
---
apiVersion: v1
kind: Secret
metadata:
  name: securechat-db-app
type: kubernetes.io/basic-auth
stringData:
  username: chat_admin
  password: SecureDbPassword123!
